version: "3.9"
services:
  XPRODB:
    image: doctorkirk/oracle-19c
    environment:
      - ORACLE_DATABASE=XPRODB
      - ORACLE_USERNAME=XADMIN
      - ORACLE_PASSWORD=XADMIN
    ports:
      - 1501:1521
    volumes:
      - C:\Users\USER\IdeaProjects\study\jpa_multi_db\docker\xprodb\oracle-19c\oradata:/opt/oracle/oradata
  YPRODB:
    image: doctorkirk/oracle-19c
    environment:
      - ORACLE_DATABASE=XPRODB
      - ORACLE_USERNAME=XADMIN
      - ORACLE_PASSWORD=XADMIN
    ports:
      - 1502:1521
    volumes:
      - C:\Users\USER\IdeaProjects\study\jpa_multi_db\docker\yprodb\oracle-19c\oradata:/opt/oracle/oradata
  IPRODB:
    image: doctorkirk/oracle-19c
    environment:
      - ORACLE_DATABASE=XPRODB
      - ORACLE_USERNAME=XADMIN
      - ORACLE_PASSWORD=XADMIN
    ports:
      - 1503:1521
    volumes:
      - C:\Users\USER\IdeaProjects\study\jpa_multi_db\docker\iprodb\oracle-19c\oradata:/opt/oracle/oradata
  KPRODB:
    image: doctorkirk/oracle-19c
    environment:
      - ORACLE_DATABASE=XPRODB
      - ORACLE_USERNAME=XADMIN
      - ORACLE_PASSWORD=XADMIN
    ports:
      - 1504:1521
    volumes:
      - C:\Users\USER\IdeaProjects\study\jpa_multi_db\docker\kprodb\oracle-19c\oradata:/opt/oracle/oradata
  XBIZDB:
    image: doctorkirk/oracle-19c
    environment:
      - ORACLE_DATABASE=XPRODB
      - ORACLE_USERNAME=XADMIN
      - ORACLE_PASSWORD=XADMIN
    ports:
      - 1505:1521
    volumes:
      - C:\Users\USER\IdeaProjects\study\jpa_multi_db\docker\xbizdb\oracle-19c\oradata:/opt/oracle/oradata