version: "3.9"
services:
  XPRODB:
    image: postgres:latest
    ports:
      - "5501:5432"
    environment:
      POSTGRES_USER: XADMIN
      POSTGRES_PASSWORD: XADMIN
      POSTGRES_DB: XPRODB
      TZ: "Asia/Seoul"
    restart: always
    container_name: XPRODB_postgres
    volumes:
      - ./init:/docker-entrypoint-initdb.d/

  YPRODB:
    image: postgres:latest
    ports:
      - "5502:5432"
    environment:
      POSTGRES_USER: XADMIN
      POSTGRES_PASSWORD: XADMIN
      POSTGRES_DB: YPRODB
      TZ: "Asia/Seoul"
    restart: always
    container_name: YPRODB_postgres
    volumes:
      - ./init:/docker-entrypoint-initdb.d/

  IPRODB:
    image: postgres:latest
    ports:
      - "5503:5432"
    environment:
      POSTGRES_USER: XADMIN
      POSTGRES_PASSWORD: XADMIN
      POSTGRES_DB: IPRODB
      TZ: "Asia/Seoul"
    restart: always
    container_name: IPRODB_postgres
    volumes:
      - ./init:/docker-entrypoint-initdb.d/

  KPRODB:
    image: postgres:latest
    ports:
      - "5504:5432"
    environment:
      POSTGRES_USER: XADMIN
      POSTGRES_PASSWORD: XADMIN
      POSTGRES_DB: KPRODB
      TZ: "Asia/Seoul"
    restart: always
    container_name: KPRODB_postgres
    volumes:
      - ./init:/docker-entrypoint-initdb.d/

  XBIZDB:
    image: postgres:latest
    ports:
      - "5505:5432"
    environment:
      POSTGRES_USER: XADMIN
      POSTGRES_PASSWORD: XADMIN
      POSTGRES_DB: XBIZDB
      TZ: "Asia/Seoul"
    restart: always
    container_name: XBIZDB_postgres
    volumes:
      - ./init:/docker-entrypoint-initdb.d/