version: "3.9"
services:
  xprodb:
    image: doctorkirk/oracle-19c
    restart: always
    ports:
      - 1501:1521
    environment:
      ORACLE_SID: XPRODB
      ORACLE_HOME: /opt/oracle/xe
      ORACLE_PDB: XPRODB
      ORACLE_USER: XADMIN
      ORACLE_PASSWORD: XADMIN
    volumes:
      - C:\Users\USER\IdeaProjects\study\jpa_multi_db\docker\xprodb\oracle-19c\oradata:/opt/oracle/oradata
  yprodb:
    image: doctorkirk/oracle-19c
    restart: always
    ports:
      - 1502:1521
    environment:
      ORACLE_SID: YPRODB
      ORACLE_HOME: /opt/oracle/xe
      ORACLE_PDB: YPRODB
      ORACLE_USER: XADMIN
      ORACLE_PASSWORD: XADMIN
    volumes:
      - C:\Users\USER\IdeaProjects\study\jpa_multi_db\docker\yprodb\oracle-19c\oradata:/opt/oracle/oradata
  iprodb:
    image: doctorkirk/oracle-19c
    restart: always
    ports:
      - 1503:1521
    environment:
      ORACLE_SID: IPRODB
      ORACLE_HOME: /opt/oracle/xe
      ORACLE_PDB: IPRODB
      ORACLE_USER: XADMIN
      ORACLE_PASSWORD: XADMIN
    volumes:
      - C:\Users\USER\IdeaProjects\study\jpa_multi_db\docker\iprodb\oracle-19c\oradata:/opt/oracle/oradata
  kprodb:
    image: doctorkirk/oracle-19c
    restart: always
    ports:
      - 1504:1521
    environment:
      ORACLE_SID: KPRODB
      ORACLE_HOME: /opt/oracle/xe
      ORACLE_PDB: KPRODB
      ORACLE_USER: XADMIN
      ORACLE_PASSWORD: XADMIN
    volumes:
      - C:\Users\USER\IdeaProjects\study\jpa_multi_db\docker\kprodb\oracle-19c\oradata:/opt/oracle/oradata
  xbizdb:
    image: doctorkirk/oracle-19c
    restart: always
    ports:
      - 1505:1521
    environment:
      ORACLE_SID: XBIZDB
      ORACLE_HOME: /opt/oracle/xe
      ORACLE_PDB: XBIZDB
      ORACLE_USER: XADMIN
      ORACLE_PASSWORD: XADMIN
    volumes:
      - C:\Users\USER\IdeaProjects\study\jpa_multi_db\docker\xbizdb\oracle-19c\oradata:/opt/oracle/oradata