spring:
  port: 8888
  application:
    name: jpa-multi-db-test
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        # show_sql: true
        default_batch_fetch_size: 500
  datasource:
    url: jdbc:postgresql://localhost:5501/XPRODB
    username: XADMIN
    password: XADMIN
    driver-class-name: org.postgresql.Driver
  YPRODB-datasource:
    url: jdbc:postgresql://localhost:5502/YPRODB
    username: XADMIN
    password: XADMIN
    driver-class-name: org.postgresql.Driver
  IPRODB-datasource:
    url: jdbc:postgresql://localhost:5503/IPRODB
    username: XADMIN
    password: XADMIN
    driver-class-name: org.postgresql.Driver
  KPRODB-datasource:
    url: jdbc:postgresql://localhost:5504/KPRODB
    username: XADMIN
    password: XADMIN
    driver-class-name: org.postgresql.Driver
  XBIZDB-datasource:
    url: jdbc:postgresql://localhost:5505/XBIZDB
    username: XADMIN
    password: XADMIN
    driver-class-name: org.postgresql.Driver